spring:
  config:
    import: optional:file:./config/env/local.env[.properties]

  security:
    oauth2:
      kakao:
        client-id: 28d0cd3dbac0f2ebb39cc230d4ac0c92
        redirect-uri: http://localhost:8080/auth/social/kakao
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect_uri: ${GITHUB_REDIRECT_URI}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  data:
    redis:
      host: 10.124.81.3
      port: 6379
    mongodb:
      uri: mongodb+srv://workspace_db:kakao_workspace_mongo123@workspace-mongo-cluster.7fbnadz.mongodb.net/workspace?retryWrites=true&w=majority&appName=workspace-mongo-cluster
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/local,classpath:db/migration/private/local

cloud:
  aws:
    credentials:
      accessKey: dummy
      secretKey: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy

jwt:
  secret: bXktbG9jYWwtand0LXNlY3JldC1rZXktMTIzNDU2Nzg5MA==
  accessExpiration: 3600000   # 1시간(밀리초)
  refreshExpiration: 1209600000 # 2주(밀리초)

jasypt:
  encryptor:
    password: coHz1LV/CTd1/g5sS3R2YHdg6iV/TcP9I8id7Doch6A=
    algorithm: PBEWithMD5AndDES
